menu:
  home: /
  archives: /archives
  tags: /tags
  about: /about

customize:
  favicon: favicon.ico

plugins:
  google_analytics:
  google_site_verification:
  baidu_analytics:
  mathjax:
    enable: true
  fancybox:
    enable: true
  mermaid: ## mermaid url https://github.com/knsv/mermaid
    enable: true  # default true
    options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js

comment:
  disqus:

miscellaneous:
  open_graph: # http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  # links:
